### ISSUE TITLE
lib/terminfo not in taball

### ISSUE THREAD

**Issue by majidaldo** [AnacondaRecipes/ncurses-feedstock#2]
in the "fixing permissions" process

```
...
    setting rpath to: $ORIGIN/.
Warning: rpath /usr/local/conda-bld/ncurses_1515469404486/_build_env/lib is outside prefix /usr/local/conda-bld/ncurses_1515469404486/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
patchelf: file: /usr/local/conda-bld/ncurses_1515469404486/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libtinfow.so.6.0
    setting rpath to: $ORIGIN/.
Warning: rpath /usr/local/conda-bld/ncurses_1515469404486/_build_env/lib is outside prefix /usr/local/conda-bld/ncurses_1515469404486/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place (removing it)
patchelf: file: /usr/local/conda-bld/ncurses_1515469404486/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libpanelw.so.6.0
    setting rpath to: $ORIGIN/.
Fixing permissions
Detected hard-coded path in binary file share/terminfo/v/vt525
Detected hard-coded path in binary file share/terminfo/w/wsvt25
Detected hard-coded path in binary file share/terminfo/w/wsvt25m
Detected hard-coded path in binary file share/terminfo/x/x68k
Detected hard-coded path in binary file share/terminfo/z/z29a
Detected hard-coded path in binary file share/terminfo/z/z29a-kc-uc
Detected hard-coded path in binary file share/terminfo/z/z29a-nkc-bc
Detected hard-coded path in binary file share/terminfo/z/z29a-nkc-uc
Detected hard-coded path in binary file share/terminfo/z/z340
Detected hard-coded path in binary file share/terminfo/z/z340-nam
'lib/terminfo' not in tarball
Traceback (most recent call last):
  File "/usr/local/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 393, in main
    execute(sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 384, in execute
    verify=args.verify)
  File "/usr/local/lib/python3.6/site-packages/conda_build/api.py", line 186, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/usr/local/lib/python3.6/site-packages/conda_build/build.py", line 1909, in build_tree
    notest=notest,
  File "/usr/local/lib/python3.6/site-packages/conda_build/build.py", line 1341, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/usr/local/lib/python3.6/site-packages/conda_build/build.py", line 854, in bundle_conda
    tarcheck.check_all(tmp_path, metadata.config)
  File "/usr/local/lib/python3.6/site-packages/conda_build/tarcheck.py", line 89, in check_all
    x.info_files()
  File "/usr/local/lib/python3.6/site-packages/conda_build/tarcheck.py", line 53, in info_files
    raise Exception('info/files')

  File "/usr/local/lib/python3.6/site-packages/conda_build/api.py", line 186, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/usr/local/lib/python3.6/site-packages/conda_build/build.py", line 1909, in build_tree
    notest=notest,
  File "/usr/local/lib/python3.6/site-packages/conda_build/build.py", line 1341, in build
    built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
  File "/usr/local/lib/python3.6/site-packages/conda_build/build.py", line 854, in bundle_conda
    tarcheck.check_all(tmp_path, metadata.config)
  File "/usr/local/lib/python3.6/site-packages/conda_build/tarcheck.py", line 89, in check_all
    x.info_files()
  File "/usr/local/lib/python3.6/site-packages/conda_build/tarcheck.py", line 53, in info_files
    raise Exception('info/files')
```
  
  
lib/terminfo is a directory. how did it manifest as a file in the tarball?

**Comment by majidaldo** [comment]
it builds if i put this in `build.sh`. not sure  how it will affect dependent packages.

```
 rm -rf "${PREFIX}"/lib/terminfo
 cp -R "${PREFIX}"/share/terminfo "${PREFIX}"/lib/terminfo/
```
